<Project Sdk="Aspire.AppHost.Sdk/13.3.5">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.3.5" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="13.3.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TodoApp.Api\TodoApp.Api.csproj" />
    <ProjectReference Include="..\TodoApp.Broker\TodoApp.Broker.csproj" />
    <ProjectReference Include="..\TodoApp.Identity\TodoApp.Identity.csproj" />
    <ProjectReference Include="..\TodoApp.WebApp\TodoApp.WebApp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TodoApp.IntegrationTests" />
  </ItemGroup>

</Project>
